// Code generated by protoc-gen-go. DO NOT EDIT.
// source: king.proto

/*
Package king is a generated protocol buffer package.

--0

It is generated from these files:
	king.proto

It has these top-level messages:
	C2S_Login
	S2C_Login
	S2C_ErrMsg
	C2S_Ping
	S2C_Ping
	C2S_Heart
	S2C_Heart
	C2S_ReConnect
	S2C_ReConnect
	C2S_GetInitGame
	Hero
	PlayerInfo
	Building
	Army
	S2C_GetInitGame
	C2S_AttackNpc
	S2C_AttackNpc
	C2S_AttackNpcReleaseSkill
	TargetBeAction
	BattleAction
	BattleEvent
	Round
	HeroResult
	BattleResult
	S2C_AttackNpcReleaseSkill
	C2S_Sign
	GiftInfo
	S2C_Sign
	C2S_GetSignInfo
	S2C_GetSignInfo
	C2S_GetRedPoint
	S2C_GetRedPoint
	C2S_GetRankInfo
	S2C_GetRankInfo
	C2S_BuyHero
	S2C_BuyHero
	C2S_EnQueue
	S2C_EnQueue
	C2S_SetDefArmy
	S2C_SetDefArmy
	C2S_EnQueueSingle
	S2C_EnQueueSingle
	C2S_HeroRecruit
	S2C_HeroRecruit
	C2S_FreeHeroRecruit
	S2C_FreeHeroRecruit
	C2S_FightPVE
	S2C_FightPVE
	C2S_GetPVELevelId
	S2C_GetPVELevelId
	C2S_ContinueFight
	S2C_ContinueFight
*/
package king

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// /////////////////////////////////////登陆及连接维护等协议 begin----------------------------------------**
// /登陆/////////////////////////////////////////////////////////////////////////
// open_id 为 从sdk那里获取到的sessionid(因历史原因没有改字段名)
// name 跟 url 如果玩家有授权就发过来，如果没有，就发长度为0的字符串
// --100
type C2S_Login struct {
	OpenId           *string `protobuf:"bytes,1,req,name=open_id,json=openId" json:"open_id,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Url              *string `protobuf:"bytes,3,req,name=url" json:"url,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *C2S_Login) Reset()                    { *m = C2S_Login{} }
func (m *C2S_Login) String() string            { return proto.CompactTextString(m) }
func (*C2S_Login) ProtoMessage()               {}
func (*C2S_Login) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *C2S_Login) GetOpenId() string {
	if m != nil && m.OpenId != nil {
		return *m.OpenId
	}
	return ""
}

func (m *C2S_Login) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *C2S_Login) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

// 返回player_id
// --101
type S2C_Login struct {
	PlayerId         *int32  `protobuf:"varint,1,req,name=player_id,json=playerId" json:"player_id,omitempty"`
	Token            *string `protobuf:"bytes,2,req,name=token" json:"token,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *S2C_Login) Reset()                    { *m = S2C_Login{} }
func (m *S2C_Login) String() string            { return proto.CompactTextString(m) }
func (*S2C_Login) ProtoMessage()               {}
func (*S2C_Login) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *S2C_Login) GetPlayerId() int32 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *S2C_Login) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

// /错误协议返回，除非特殊的协议，否则所有的协议在错误判断不通过时，都返回这条协议/////////////////////////////////////////////////////////////////////////
// --102
type S2C_ErrMsg struct {
	Err              *int32 `protobuf:"varint,1,req,name=err" json:"err,omitempty"`
	ProtoId          *int32 `protobuf:"varint,2,req,name=protoId" json:"protoId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *S2C_ErrMsg) Reset()                    { *m = S2C_ErrMsg{} }
func (m *S2C_ErrMsg) String() string            { return proto.CompactTextString(m) }
func (*S2C_ErrMsg) ProtoMessage()               {}
func (*S2C_ErrMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *S2C_ErrMsg) GetErr() int32 {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return 0
}

func (m *S2C_ErrMsg) GetProtoId() int32 {
	if m != nil && m.ProtoId != nil {
		return *m.ProtoId
	}
	return 0
}

// /ping协议
// --103
type C2S_Ping struct {
	ClientTimestamp  *int32 `protobuf:"varint,1,req,name=clientTimestamp" json:"clientTimestamp,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *C2S_Ping) Reset()                    { *m = C2S_Ping{} }
func (m *C2S_Ping) String() string            { return proto.CompactTextString(m) }
func (*C2S_Ping) ProtoMessage()               {}
func (*C2S_Ping) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *C2S_Ping) GetClientTimestamp() int32 {
	if m != nil && m.ClientTimestamp != nil {
		return *m.ClientTimestamp
	}
	return 0
}

// --104
type S2C_Ping struct {
	ClientTimestamp  *int32 `protobuf:"varint,1,req,name=clientTimestamp" json:"clientTimestamp,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *S2C_Ping) Reset()                    { *m = S2C_Ping{} }
func (m *S2C_Ping) String() string            { return proto.CompactTextString(m) }
func (*S2C_Ping) ProtoMessage()               {}
func (*S2C_Ping) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *S2C_Ping) GetClientTimestamp() int32 {
	if m != nil && m.ClientTimestamp != nil {
		return *m.ClientTimestamp
	}
	return 0
}

// /heart协议
// --105
type C2S_Heart struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *C2S_Heart) Reset()                    { *m = C2S_Heart{} }
func (m *C2S_Heart) String() string            { return proto.CompactTextString(m) }
func (*C2S_Heart) ProtoMessage()               {}
func (*C2S_Heart) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

// --106
type S2C_Heart struct {
	ServerTimestamp  *int32 `protobuf:"varint,1,req,name=serverTimestamp" json:"serverTimestamp,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *S2C_Heart) Reset()                    { *m = S2C_Heart{} }
func (m *S2C_Heart) String() string            { return proto.CompactTextString(m) }
func (*S2C_Heart) ProtoMessage()               {}
func (*S2C_Heart) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *S2C_Heart) GetServerTimestamp() int32 {
	if m != nil && m.ServerTimestamp != nil {
		return *m.ServerTimestamp
	}
	return 0
}

// //当短暂断线的时候，发送此协议 代替登陆协议（因为登陆协议需要走平台，时间比较久）////////
// --107
type C2S_ReConnect struct {
	OpenId           *string `protobuf:"bytes,1,req,name=open_id,json=openId" json:"open_id,omitempty"`
	PlayerId         *int32  `protobuf:"varint,2,req,name=player_id,json=playerId" json:"player_id,omitempty"`
	Token            *string `protobuf:"bytes,3,req,name=token" json:"token,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *C2S_ReConnect) Reset()                    { *m = C2S_ReConnect{} }
func (m *C2S_ReConnect) String() string            { return proto.CompactTextString(m) }
func (*C2S_ReConnect) ProtoMessage()               {}
func (*C2S_ReConnect) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *C2S_ReConnect) GetOpenId() string {
	if m != nil && m.OpenId != nil {
		return *m.OpenId
	}
	return ""
}

func (m *C2S_ReConnect) GetPlayerId() int32 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *C2S_ReConnect) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

// --108
type S2C_ReConnect struct {
	PlayerId         *int32 `protobuf:"varint,1,req,name=player_id,json=playerId" json:"player_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *S2C_ReConnect) Reset()                    { *m = S2C_ReConnect{} }
func (m *S2C_ReConnect) String() string            { return proto.CompactTextString(m) }
func (*S2C_ReConnect) ProtoMessage()               {}
func (*S2C_ReConnect) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *S2C_ReConnect) GetPlayerId() int32 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

// /////////////////////////////////////战斗相关协议 begin----------------------------------------**
// /////----------------
// 初始化游戏相关信息
// --200
type C2S_GetInitGame struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *C2S_GetInitGame) Reset()                    { *m = C2S_GetInitGame{} }
func (m *C2S_GetInitGame) String() string            { return proto.CompactTextString(m) }
func (*C2S_GetInitGame) ProtoMessage()               {}
func (*C2S_GetInitGame) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type Hero struct {
	Id               *int32 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Exp              *int32 `protobuf:"varint,2,req,name=exp" json:"exp,omitempty"`
	Level            *int32 `protobuf:"varint,3,req,name=level" json:"level,omitempty"`
	Star             *int32 `protobuf:"varint,4,req,name=star" json:"star,omitempty"`
	ArmyLv           *int32 `protobuf:"varint,5,req,name=armyLv" json:"armyLv,omitempty"`
	ArmySkill1Lv     *int32 `protobuf:"varint,6,req,name=armySkill1Lv" json:"armySkill1Lv,omitempty"`
	ArmySkill2Lv     *int32 `protobuf:"varint,7,req,name=armySkill2Lv" json:"armySkill2Lv,omitempty"`
	ArmySkill3Lv     *int32 `protobuf:"varint,8,req,name=armySkill3Lv" json:"armySkill3Lv,omitempty"`
	Chip             *int32 `protobuf:"varint,9,req,name=chip" json:"chip,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Hero) Reset()                    { *m = Hero{} }
func (m *Hero) String() string            { return proto.CompactTextString(m) }
func (*Hero) ProtoMessage()               {}
func (*Hero) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *Hero) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Hero) GetExp() int32 {
	if m != nil && m.Exp != nil {
		return *m.Exp
	}
	return 0
}

func (m *Hero) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *Hero) GetStar() int32 {
	if m != nil && m.Star != nil {
		return *m.Star
	}
	return 0
}

func (m *Hero) GetArmyLv() int32 {
	if m != nil && m.ArmyLv != nil {
		return *m.ArmyLv
	}
	return 0
}

func (m *Hero) GetArmySkill1Lv() int32 {
	if m != nil && m.ArmySkill1Lv != nil {
		return *m.ArmySkill1Lv
	}
	return 0
}

func (m *Hero) GetArmySkill2Lv() int32 {
	if m != nil && m.ArmySkill2Lv != nil {
		return *m.ArmySkill2Lv
	}
	return 0
}

func (m *Hero) GetArmySkill3Lv() int32 {
	if m != nil && m.ArmySkill3Lv != nil {
		return *m.ArmySkill3Lv
	}
	return 0
}

func (m *Hero) GetChip() int32 {
	if m != nil && m.Chip != nil {
		return *m.Chip
	}
	return 0
}

type PlayerInfo struct {
	Coin             *int32 `protobuf:"varint,1,req,name=coin" json:"coin,omitempty"`
	Diamond          *int32 `protobuf:"varint,2,req,name=diamond" json:"diamond,omitempty"`
	Level            *int32 `protobuf:"varint,3,req,name=level" json:"level,omitempty"`
	Wood             *int32 `protobuf:"varint,4,req,name=wood" json:"wood,omitempty"`
	Mineral          *int32 `protobuf:"varint,5,req,name=mineral" json:"mineral,omitempty"`
	Grain            *int32 `protobuf:"varint,6,req,name=grain" json:"grain,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerInfo) Reset()                    { *m = PlayerInfo{} }
func (m *PlayerInfo) String() string            { return proto.CompactTextString(m) }
func (*PlayerInfo) ProtoMessage()               {}
func (*PlayerInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *PlayerInfo) GetCoin() int32 {
	if m != nil && m.Coin != nil {
		return *m.Coin
	}
	return 0
}

func (m *PlayerInfo) GetDiamond() int32 {
	if m != nil && m.Diamond != nil {
		return *m.Diamond
	}
	return 0
}

func (m *PlayerInfo) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *PlayerInfo) GetWood() int32 {
	if m != nil && m.Wood != nil {
		return *m.Wood
	}
	return 0
}

func (m *PlayerInfo) GetMineral() int32 {
	if m != nil && m.Mineral != nil {
		return *m.Mineral
	}
	return 0
}

func (m *PlayerInfo) GetGrain() int32 {
	if m != nil && m.Grain != nil {
		return *m.Grain
	}
	return 0
}

type Building struct {
	Farm1Lv          *int32 `protobuf:"varint,1,req,name=farm1Lv" json:"farm1Lv,omitempty"`
	Farm2Lv          *int32 `protobuf:"varint,2,req,name=farm2Lv" json:"farm2Lv,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Building) Reset()                    { *m = Building{} }
func (m *Building) String() string            { return proto.CompactTextString(m) }
func (*Building) ProtoMessage()               {}
func (*Building) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *Building) GetFarm1Lv() int32 {
	if m != nil && m.Farm1Lv != nil {
		return *m.Farm1Lv
	}
	return 0
}

func (m *Building) GetFarm2Lv() int32 {
	if m != nil && m.Farm2Lv != nil {
		return *m.Farm2Lv
	}
	return 0
}

type Army struct {
	ArmyId           *int32  `protobuf:"varint,1,req,name=armyId" json:"armyId,omitempty"`
	HeroIds          []int32 `protobuf:"varint,2,rep,name=heroIds" json:"heroIds,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Army) Reset()                    { *m = Army{} }
func (m *Army) String() string            { return proto.CompactTextString(m) }
func (*Army) ProtoMessage()               {}
func (*Army) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *Army) GetArmyId() int32 {
	if m != nil && m.ArmyId != nil {
		return *m.ArmyId
	}
	return 0
}

func (m *Army) GetHeroIds() []int32 {
	if m != nil {
		return m.HeroIds
	}
	return nil
}

// --201
type S2C_GetInitGame struct {
	Armys            []*Army     `protobuf:"bytes,1,rep,name=armys" json:"armys,omitempty"`
	Building         *Building   `protobuf:"bytes,2,req,name=building" json:"building,omitempty"`
	Heros            []*Hero     `protobuf:"bytes,3,rep,name=heros" json:"heros,omitempty"`
	PlayerInfo       *PlayerInfo `protobuf:"bytes,4,req,name=playerInfo" json:"playerInfo,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *S2C_GetInitGame) Reset()                    { *m = S2C_GetInitGame{} }
func (m *S2C_GetInitGame) String() string            { return proto.CompactTextString(m) }
func (*S2C_GetInitGame) ProtoMessage()               {}
func (*S2C_GetInitGame) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *S2C_GetInitGame) GetArmys() []*Army {
	if m != nil {
		return m.Armys
	}
	return nil
}

func (m *S2C_GetInitGame) GetBuilding() *Building {
	if m != nil {
		return m.Building
	}
	return nil
}

func (m *S2C_GetInitGame) GetHeros() []*Hero {
	if m != nil {
		return m.Heros
	}
	return nil
}

func (m *S2C_GetInitGame) GetPlayerInfo() *PlayerInfo {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

// /////----------------
// change to attackplayer
// --202
type C2S_AttackNpc struct {
	ArmyId           *int32 `protobuf:"varint,1,req,name=armyId" json:"armyId,omitempty"`
	NpcId            *int32 `protobuf:"varint,2,req,name=npcId" json:"npcId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *C2S_AttackNpc) Reset()                    { *m = C2S_AttackNpc{} }
func (m *C2S_AttackNpc) String() string            { return proto.CompactTextString(m) }
func (*C2S_AttackNpc) ProtoMessage()               {}
func (*C2S_AttackNpc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *C2S_AttackNpc) GetArmyId() int32 {
	if m != nil && m.ArmyId != nil {
		return *m.ArmyId
	}
	return 0
}

func (m *C2S_AttackNpc) GetNpcId() int32 {
	if m != nil && m.NpcId != nil {
		return *m.NpcId
	}
	return 0
}

// --203
type S2C_AttackNpc struct {
	ArmyId           *int32 `protobuf:"varint,1,req,name=armyId" json:"armyId,omitempty"`
	NpcId            *int32 `protobuf:"varint,2,req,name=npcId" json:"npcId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *S2C_AttackNpc) Reset()                    { *m = S2C_AttackNpc{} }
func (m *S2C_AttackNpc) String() string            { return proto.CompactTextString(m) }
func (*S2C_AttackNpc) ProtoMessage()               {}
func (*S2C_AttackNpc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *S2C_AttackNpc) GetArmyId() int32 {
	if m != nil && m.ArmyId != nil {
		return *m.ArmyId
	}
	return 0
}

func (m *S2C_AttackNpc) GetNpcId() int32 {
	if m != nil && m.NpcId != nil {
		return *m.NpcId
	}
	return 0
}

// --204
type C2S_AttackNpcReleaseSkill struct {
	HeroId           *int32 `protobuf:"varint,1,req,name=heroId" json:"heroId,omitempty"`
	Round            *int32 `protobuf:"varint,2,req,name=round" json:"round,omitempty"`
	Step             *int32 `protobuf:"varint,3,req,name=step" json:"step,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *C2S_AttackNpcReleaseSkill) Reset()                    { *m = C2S_AttackNpcReleaseSkill{} }
func (m *C2S_AttackNpcReleaseSkill) String() string            { return proto.CompactTextString(m) }
func (*C2S_AttackNpcReleaseSkill) ProtoMessage()               {}
func (*C2S_AttackNpcReleaseSkill) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *C2S_AttackNpcReleaseSkill) GetHeroId() int32 {
	if m != nil && m.HeroId != nil {
		return *m.HeroId
	}
	return 0
}

func (m *C2S_AttackNpcReleaseSkill) GetRound() int32 {
	if m != nil && m.Round != nil {
		return *m.Round
	}
	return 0
}

func (m *C2S_AttackNpcReleaseSkill) GetStep() int32 {
	if m != nil && m.Step != nil {
		return *m.Step
	}
	return 0
}

type TargetBeAction struct {
	Pos              *int32  `protobuf:"varint,1,req,name=pos" json:"pos,omitempty"`
	Values           []int32 `protobuf:"varint,2,rep,name=values" json:"values,omitempty"`
	Type             *int32  `protobuf:"varint,3,req,name=type" json:"type,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TargetBeAction) Reset()                    { *m = TargetBeAction{} }
func (m *TargetBeAction) String() string            { return proto.CompactTextString(m) }
func (*TargetBeAction) ProtoMessage()               {}
func (*TargetBeAction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *TargetBeAction) GetPos() int32 {
	if m != nil && m.Pos != nil {
		return *m.Pos
	}
	return 0
}

func (m *TargetBeAction) GetValues() []int32 {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *TargetBeAction) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

type BattleAction struct {
	AttackPos        *int32            `protobuf:"varint,1,req,name=attackPos" json:"attackPos,omitempty"`
	SkillId          *int32            `protobuf:"varint,2,req,name=skillId" json:"skillId,omitempty"`
	TargetBeActions  []*TargetBeAction `protobuf:"bytes,3,rep,name=targetBeActions" json:"targetBeActions,omitempty"`
	EventIds         []int32           `protobuf:"varint,4,rep,name=eventIds" json:"eventIds,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *BattleAction) Reset()                    { *m = BattleAction{} }
func (m *BattleAction) String() string            { return proto.CompactTextString(m) }
func (*BattleAction) ProtoMessage()               {}
func (*BattleAction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *BattleAction) GetAttackPos() int32 {
	if m != nil && m.AttackPos != nil {
		return *m.AttackPos
	}
	return 0
}

func (m *BattleAction) GetSkillId() int32 {
	if m != nil && m.SkillId != nil {
		return *m.SkillId
	}
	return 0
}

func (m *BattleAction) GetTargetBeActions() []*TargetBeAction {
	if m != nil {
		return m.TargetBeActions
	}
	return nil
}

func (m *BattleAction) GetEventIds() []int32 {
	if m != nil {
		return m.EventIds
	}
	return nil
}

type BattleEvent struct {
	Id               *int32 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Pos              *int32 `protobuf:"varint,2,req,name=pos" json:"pos,omitempty"`
	Type             *int32 `protobuf:"varint,3,req,name=type" json:"type,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *BattleEvent) Reset()                    { *m = BattleEvent{} }
func (m *BattleEvent) String() string            { return proto.CompactTextString(m) }
func (*BattleEvent) ProtoMessage()               {}
func (*BattleEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *BattleEvent) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *BattleEvent) GetPos() int32 {
	if m != nil && m.Pos != nil {
		return *m.Pos
	}
	return 0
}

func (m *BattleEvent) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

// round=0时，为战前回合，此时会释放概率性buf技能
type Round struct {
	BattleActions    []*BattleAction `protobuf:"bytes,1,rep,name=battleActions" json:"battleActions,omitempty"`
	BattleEvents     []*BattleEvent  `protobuf:"bytes,2,rep,name=battleEvents" json:"battleEvents,omitempty"`
	Round            *int32          `protobuf:"varint,3,req,name=round" json:"round,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Round) Reset()                    { *m = Round{} }
func (m *Round) String() string            { return proto.CompactTextString(m) }
func (*Round) ProtoMessage()               {}
func (*Round) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *Round) GetBattleActions() []*BattleAction {
	if m != nil {
		return m.BattleActions
	}
	return nil
}

func (m *Round) GetBattleEvents() []*BattleEvent {
	if m != nil {
		return m.BattleEvents
	}
	return nil
}

func (m *Round) GetRound() int32 {
	if m != nil && m.Round != nil {
		return *m.Round
	}
	return 0
}

type HeroResult struct {
	Pos              *int32 `protobuf:"varint,1,req,name=pos" json:"pos,omitempty"`
	HeroId           *int32 `protobuf:"varint,2,req,name=heroId" json:"heroId,omitempty"`
	Troops           *int32 `protobuf:"varint,3,req,name=troops" json:"troops,omitempty"`
	InitTroops       *int32 `protobuf:"varint,4,req,name=initTroops" json:"initTroops,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *HeroResult) Reset()                    { *m = HeroResult{} }
func (m *HeroResult) String() string            { return proto.CompactTextString(m) }
func (*HeroResult) ProtoMessage()               {}
func (*HeroResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *HeroResult) GetPos() int32 {
	if m != nil && m.Pos != nil {
		return *m.Pos
	}
	return 0
}

func (m *HeroResult) GetHeroId() int32 {
	if m != nil && m.HeroId != nil {
		return *m.HeroId
	}
	return 0
}

func (m *HeroResult) GetTroops() int32 {
	if m != nil && m.Troops != nil {
		return *m.Troops
	}
	return 0
}

func (m *HeroResult) GetInitTroops() int32 {
	if m != nil && m.InitTroops != nil {
		return *m.InitTroops
	}
	return 0
}

type BattleResult struct {
	ArmyId           *int32        `protobuf:"varint,1,req,name=armyId" json:"armyId,omitempty"`
	Rounds           []*Round      `protobuf:"bytes,2,rep,name=rounds" json:"rounds,omitempty"`
	Result           *int32        `protobuf:"varint,3,req,name=result" json:"result,omitempty"`
	HeroResults      []*HeroResult `protobuf:"bytes,4,rep,name=heroResults" json:"heroResults,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *BattleResult) Reset()                    { *m = BattleResult{} }
func (m *BattleResult) String() string            { return proto.CompactTextString(m) }
func (*BattleResult) ProtoMessage()               {}
func (*BattleResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *BattleResult) GetArmyId() int32 {
	if m != nil && m.ArmyId != nil {
		return *m.ArmyId
	}
	return 0
}

func (m *BattleResult) GetRounds() []*Round {
	if m != nil {
		return m.Rounds
	}
	return nil
}

func (m *BattleResult) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *BattleResult) GetHeroResults() []*HeroResult {
	if m != nil {
		return m.HeroResults
	}
	return nil
}

// 进攻城池的结果
// --205
type S2C_AttackNpcReleaseSkill struct {
	BattleResult     *BattleResult `protobuf:"bytes,1,req,name=battleResult" json:"battleResult,omitempty"`
	HeroId           *int32        `protobuf:"varint,2,req,name=heroId" json:"heroId,omitempty"`
	Round            *int32        `protobuf:"varint,3,req,name=round" json:"round,omitempty"`
	Step             *int32        `protobuf:"varint,4,req,name=step" json:"step,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *S2C_AttackNpcReleaseSkill) Reset()                    { *m = S2C_AttackNpcReleaseSkill{} }
func (m *S2C_AttackNpcReleaseSkill) String() string            { return proto.CompactTextString(m) }
func (*S2C_AttackNpcReleaseSkill) ProtoMessage()               {}
func (*S2C_AttackNpcReleaseSkill) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *S2C_AttackNpcReleaseSkill) GetBattleResult() *BattleResult {
	if m != nil {
		return m.BattleResult
	}
	return nil
}

func (m *S2C_AttackNpcReleaseSkill) GetHeroId() int32 {
	if m != nil && m.HeroId != nil {
		return *m.HeroId
	}
	return 0
}

func (m *S2C_AttackNpcReleaseSkill) GetRound() int32 {
	if m != nil && m.Round != nil {
		return *m.Round
	}
	return 0
}

func (m *S2C_AttackNpcReleaseSkill) GetStep() int32 {
	if m != nil && m.Step != nil {
		return *m.Step
	}
	return 0
}

// /////////////////////////////////////其它比较零散协议 begin----------------------------------------**
// 签到
// 正常签到返回 S2C_GetSignInfo
// --300
type C2S_Sign struct {
	SignType         *int32 `protobuf:"varint,1,req,name=signType" json:"signType,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *C2S_Sign) Reset()                    { *m = C2S_Sign{} }
func (m *C2S_Sign) String() string            { return proto.CompactTextString(m) }
func (*C2S_Sign) ProtoMessage()               {}
func (*C2S_Sign) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *C2S_Sign) GetSignType() int32 {
	if m != nil && m.SignType != nil {
		return *m.SignType
	}
	return 0
}

type GiftInfo struct {
	GiftId           *int32 `protobuf:"varint,1,req,name=giftId" json:"giftId,omitempty"`
	GiftNum          *int32 `protobuf:"varint,2,req,name=giftNum" json:"giftNum,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GiftInfo) Reset()                    { *m = GiftInfo{} }
func (m *GiftInfo) String() string            { return proto.CompactTextString(m) }
func (*GiftInfo) ProtoMessage()               {}
func (*GiftInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *GiftInfo) GetGiftId() int32 {
	if m != nil && m.GiftId != nil {
		return *m.GiftId
	}
	return 0
}

func (m *GiftInfo) GetGiftNum() int32 {
	if m != nil && m.GiftNum != nil {
		return *m.GiftNum
	}
	return 0
}

// --301
type S2C_Sign struct {
	SignType         *int32      `protobuf:"varint,1,req,name=signType" json:"signType,omitempty"`
	Reward           []*GiftInfo `protobuf:"bytes,2,rep,name=reward" json:"reward,omitempty"`
	ExtReward        []*GiftInfo `protobuf:"bytes,3,rep,name=extReward" json:"extReward,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *S2C_Sign) Reset()                    { *m = S2C_Sign{} }
func (m *S2C_Sign) String() string            { return proto.CompactTextString(m) }
func (*S2C_Sign) ProtoMessage()               {}
func (*S2C_Sign) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *S2C_Sign) GetSignType() int32 {
	if m != nil && m.SignType != nil {
		return *m.SignType
	}
	return 0
}

func (m *S2C_Sign) GetReward() []*GiftInfo {
	if m != nil {
		return m.Reward
	}
	return nil
}

func (m *S2C_Sign) GetExtReward() []*GiftInfo {
	if m != nil {
		return m.ExtReward
	}
	return nil
}

// 拉取签到信息
// --302
type C2S_GetSignInfo struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *C2S_GetSignInfo) Reset()                    { *m = C2S_GetSignInfo{} }
func (m *C2S_GetSignInfo) String() string            { return proto.CompactTextString(m) }
func (*C2S_GetSignInfo) ProtoMessage()               {}
func (*C2S_GetSignInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

// --303
type S2C_GetSignInfo struct {
	WeekSignDay      *int32 `protobuf:"varint,1,req,name=weekSignDay" json:"weekSignDay,omitempty"`
	BWeekSignToday   *bool  `protobuf:"varint,2,req,name=bWeekSignToday" json:"bWeekSignToday,omitempty"`
	MonthSignDay     *int32 `protobuf:"varint,3,req,name=monthSignDay" json:"monthSignDay,omitempty"`
	BMonthSignToday  *bool  `protobuf:"varint,4,req,name=bMonthSignToday" json:"bMonthSignToday,omitempty"`
	WeekId           *int32 `protobuf:"varint,5,req,name=weekId" json:"weekId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *S2C_GetSignInfo) Reset()                    { *m = S2C_GetSignInfo{} }
func (m *S2C_GetSignInfo) String() string            { return proto.CompactTextString(m) }
func (*S2C_GetSignInfo) ProtoMessage()               {}
func (*S2C_GetSignInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *S2C_GetSignInfo) GetWeekSignDay() int32 {
	if m != nil && m.WeekSignDay != nil {
		return *m.WeekSignDay
	}
	return 0
}

func (m *S2C_GetSignInfo) GetBWeekSignToday() bool {
	if m != nil && m.BWeekSignToday != nil {
		return *m.BWeekSignToday
	}
	return false
}

func (m *S2C_GetSignInfo) GetMonthSignDay() int32 {
	if m != nil && m.MonthSignDay != nil {
		return *m.MonthSignDay
	}
	return 0
}

func (m *S2C_GetSignInfo) GetBMonthSignToday() bool {
	if m != nil && m.BMonthSignToday != nil {
		return *m.BMonthSignToday
	}
	return false
}

func (m *S2C_GetSignInfo) GetWeekId() int32 {
	if m != nil && m.WeekId != nil {
		return *m.WeekId
	}
	return 0
}

// 小红点功能
// --304
type C2S_GetRedPoint struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *C2S_GetRedPoint) Reset()                    { *m = C2S_GetRedPoint{} }
func (m *C2S_GetRedPoint) String() string            { return proto.CompactTextString(m) }
func (*C2S_GetRedPoint) ProtoMessage()               {}
func (*C2S_GetRedPoint) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

// --305
type S2C_GetRedPoint struct {
	BWeekSign        *bool  `protobuf:"varint,1,req,name=bWeekSign" json:"bWeekSign,omitempty"`
	BMonthsign       *bool  `protobuf:"varint,2,req,name=bMonthsign" json:"bMonthsign,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *S2C_GetRedPoint) Reset()                    { *m = S2C_GetRedPoint{} }
func (m *S2C_GetRedPoint) String() string            { return proto.CompactTextString(m) }
func (*S2C_GetRedPoint) ProtoMessage()               {}
func (*S2C_GetRedPoint) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *S2C_GetRedPoint) GetBWeekSign() bool {
	if m != nil && m.BWeekSign != nil {
		return *m.BWeekSign
	}
	return false
}

func (m *S2C_GetRedPoint) GetBMonthsign() bool {
	if m != nil && m.BMonthsign != nil {
		return *m.BMonthsign
	}
	return false
}

// GetRank
// --306
type C2S_GetRankInfo struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *C2S_GetRankInfo) Reset()                    { *m = C2S_GetRankInfo{} }
func (m *C2S_GetRankInfo) String() string            { return proto.CompactTextString(m) }
func (*C2S_GetRankInfo) ProtoMessage()               {}
func (*C2S_GetRankInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

// --307
type S2C_GetRankInfo struct {
	Score            *int32 `protobuf:"varint,1,req,name=score" json:"score,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *S2C_GetRankInfo) Reset()                    { *m = S2C_GetRankInfo{} }
func (m *S2C_GetRankInfo) String() string            { return proto.CompactTextString(m) }
func (*S2C_GetRankInfo) ProtoMessage()               {}
func (*S2C_GetRankInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

func (m *S2C_GetRankInfo) GetScore() int32 {
	if m != nil && m.Score != nil {
		return *m.Score
	}
	return 0
}

// /////////////////////////////////////武将协议 begin----------------------------------------**
// /////----------------
// --401
type C2S_BuyHero struct {
	ShopId           *int32 `protobuf:"varint,1,req,name=shopId" json:"shopId,omitempty"`
	PlayerId         *int32 `protobuf:"varint,2,req,name=playerId" json:"playerId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *C2S_BuyHero) Reset()                    { *m = C2S_BuyHero{} }
func (m *C2S_BuyHero) String() string            { return proto.CompactTextString(m) }
func (*C2S_BuyHero) ProtoMessage()               {}
func (*C2S_BuyHero) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{34} }

func (m *C2S_BuyHero) GetShopId() int32 {
	if m != nil && m.ShopId != nil {
		return *m.ShopId
	}
	return 0
}

func (m *C2S_BuyHero) GetPlayerId() int32 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

// --402
type S2C_BuyHero struct {
	HeroIds          []int32 `protobuf:"varint,1,rep,name=heroIds" json:"heroIds,omitempty"`
	Chip             *int32  `protobuf:"varint,2,req,name=chip" json:"chip,omitempty"`
	ToChipHeroIds    []int32 `protobuf:"varint,3,rep,name=toChipHeroIds" json:"toChipHeroIds,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *S2C_BuyHero) Reset()                    { *m = S2C_BuyHero{} }
func (m *S2C_BuyHero) String() string            { return proto.CompactTextString(m) }
func (*S2C_BuyHero) ProtoMessage()               {}
func (*S2C_BuyHero) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{35} }

func (m *S2C_BuyHero) GetHeroIds() []int32 {
	if m != nil {
		return m.HeroIds
	}
	return nil
}

func (m *S2C_BuyHero) GetChip() int32 {
	if m != nil && m.Chip != nil {
		return *m.Chip
	}
	return 0
}

func (m *S2C_BuyHero) GetToChipHeroIds() []int32 {
	if m != nil {
		return m.ToChipHeroIds
	}
	return nil
}

// /////----------------
// --403
type C2S_EnQueue struct {
	HeroId1          *int32 `protobuf:"varint,1,req,name=heroId1" json:"heroId1,omitempty"`
	HeroId2          *int32 `protobuf:"varint,2,req,name=heroId2" json:"heroId2,omitempty"`
	HeroId3          *int32 `protobuf:"varint,3,req,name=heroId3" json:"heroId3,omitempty"`
	ArmyId           *int32 `protobuf:"varint,4,req,name=armyId" json:"armyId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *C2S_EnQueue) Reset()                    { *m = C2S_EnQueue{} }
func (m *C2S_EnQueue) String() string            { return proto.CompactTextString(m) }
func (*C2S_EnQueue) ProtoMessage()               {}
func (*C2S_EnQueue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{36} }

func (m *C2S_EnQueue) GetHeroId1() int32 {
	if m != nil && m.HeroId1 != nil {
		return *m.HeroId1
	}
	return 0
}

func (m *C2S_EnQueue) GetHeroId2() int32 {
	if m != nil && m.HeroId2 != nil {
		return *m.HeroId2
	}
	return 0
}

func (m *C2S_EnQueue) GetHeroId3() int32 {
	if m != nil && m.HeroId3 != nil {
		return *m.HeroId3
	}
	return 0
}

func (m *C2S_EnQueue) GetArmyId() int32 {
	if m != nil && m.ArmyId != nil {
		return *m.ArmyId
	}
	return 0
}

// --404
type S2C_EnQueue struct {
	HeroId1          *int32 `protobuf:"varint,1,req,name=heroId1" json:"heroId1,omitempty"`
	HeroId2          *int32 `protobuf:"varint,2,req,name=heroId2" json:"heroId2,omitempty"`
	HeroId3          *int32 `protobuf:"varint,3,req,name=heroId3" json:"heroId3,omitempty"`
	ArmyId           *int32 `protobuf:"varint,4,req,name=armyId" json:"armyId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *S2C_EnQueue) Reset()                    { *m = S2C_EnQueue{} }
func (m *S2C_EnQueue) String() string            { return proto.CompactTextString(m) }
func (*S2C_EnQueue) ProtoMessage()               {}
func (*S2C_EnQueue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{37} }

func (m *S2C_EnQueue) GetHeroId1() int32 {
	if m != nil && m.HeroId1 != nil {
		return *m.HeroId1
	}
	return 0
}

func (m *S2C_EnQueue) GetHeroId2() int32 {
	if m != nil && m.HeroId2 != nil {
		return *m.HeroId2
	}
	return 0
}

func (m *S2C_EnQueue) GetHeroId3() int32 {
	if m != nil && m.HeroId3 != nil {
		return *m.HeroId3
	}
	return 0
}

func (m *S2C_EnQueue) GetArmyId() int32 {
	if m != nil && m.ArmyId != nil {
		return *m.ArmyId
	}
	return 0
}

// /////----------------
// --405
type C2S_SetDefArmy struct {
	ArmyId           *int32 `protobuf:"varint,1,req,name=armyId" json:"armyId,omitempty"`
	CityId           *int32 `protobuf:"varint,2,req,name=cityId" json:"cityId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *C2S_SetDefArmy) Reset()                    { *m = C2S_SetDefArmy{} }
func (m *C2S_SetDefArmy) String() string            { return proto.CompactTextString(m) }
func (*C2S_SetDefArmy) ProtoMessage()               {}
func (*C2S_SetDefArmy) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{38} }

func (m *C2S_SetDefArmy) GetArmyId() int32 {
	if m != nil && m.ArmyId != nil {
		return *m.ArmyId
	}
	return 0
}

func (m *C2S_SetDefArmy) GetCityId() int32 {
	if m != nil && m.CityId != nil {
		return *m.CityId
	}
	return 0
}

// --406
type S2C_SetDefArmy struct {
	ArmyId           *int32 `protobuf:"varint,1,req,name=armyId" json:"armyId,omitempty"`
	CityId           *int32 `protobuf:"varint,2,req,name=cityId" json:"cityId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *S2C_SetDefArmy) Reset()                    { *m = S2C_SetDefArmy{} }
func (m *S2C_SetDefArmy) String() string            { return proto.CompactTextString(m) }
func (*S2C_SetDefArmy) ProtoMessage()               {}
func (*S2C_SetDefArmy) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{39} }

func (m *S2C_SetDefArmy) GetArmyId() int32 {
	if m != nil && m.ArmyId != nil {
		return *m.ArmyId
	}
	return 0
}

func (m *S2C_SetDefArmy) GetCityId() int32 {
	if m != nil && m.CityId != nil {
		return *m.CityId
	}
	return 0
}

// /////----------------
// --407
type C2S_EnQueueSingle struct {
	HeroId           *int32 `protobuf:"varint,1,req,name=heroId" json:"heroId,omitempty"`
	Pos              *int32 `protobuf:"varint,2,req,name=pos" json:"pos,omitempty"`
	ArmyId           *int32 `protobuf:"varint,3,req,name=armyId" json:"armyId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *C2S_EnQueueSingle) Reset()                    { *m = C2S_EnQueueSingle{} }
func (m *C2S_EnQueueSingle) String() string            { return proto.CompactTextString(m) }
func (*C2S_EnQueueSingle) ProtoMessage()               {}
func (*C2S_EnQueueSingle) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{40} }

func (m *C2S_EnQueueSingle) GetHeroId() int32 {
	if m != nil && m.HeroId != nil {
		return *m.HeroId
	}
	return 0
}

func (m *C2S_EnQueueSingle) GetPos() int32 {
	if m != nil && m.Pos != nil {
		return *m.Pos
	}
	return 0
}

func (m *C2S_EnQueueSingle) GetArmyId() int32 {
	if m != nil && m.ArmyId != nil {
		return *m.ArmyId
	}
	return 0
}

// --408
type S2C_EnQueueSingle struct {
	HeroId           *int32 `protobuf:"varint,1,req,name=heroId" json:"heroId,omitempty"`
	Pos              *int32 `protobuf:"varint,2,req,name=pos" json:"pos,omitempty"`
	ArmyId           *int32 `protobuf:"varint,3,req,name=armyId" json:"armyId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *S2C_EnQueueSingle) Reset()                    { *m = S2C_EnQueueSingle{} }
func (m *S2C_EnQueueSingle) String() string            { return proto.CompactTextString(m) }
func (*S2C_EnQueueSingle) ProtoMessage()               {}
func (*S2C_EnQueueSingle) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{41} }

func (m *S2C_EnQueueSingle) GetHeroId() int32 {
	if m != nil && m.HeroId != nil {
		return *m.HeroId
	}
	return 0
}

func (m *S2C_EnQueueSingle) GetPos() int32 {
	if m != nil && m.Pos != nil {
		return *m.Pos
	}
	return 0
}

func (m *S2C_EnQueueSingle) GetArmyId() int32 {
	if m != nil && m.ArmyId != nil {
		return *m.ArmyId
	}
	return 0
}

// --409
type C2S_HeroRecruit struct {
	Type             *int32 `protobuf:"varint,1,req,name=type" json:"type,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *C2S_HeroRecruit) Reset()                    { *m = C2S_HeroRecruit{} }
func (m *C2S_HeroRecruit) String() string            { return proto.CompactTextString(m) }
func (*C2S_HeroRecruit) ProtoMessage()               {}
func (*C2S_HeroRecruit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{42} }

func (m *C2S_HeroRecruit) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

// --410
type S2C_HeroRecruit struct {
	HeroIds          []int32 `protobuf:"varint,1,rep,name=heroIds" json:"heroIds,omitempty"`
	ToChipHeroIds    []int32 `protobuf:"varint,2,rep,name=toChipHeroIds" json:"toChipHeroIds,omitempty"`
	Chip             *int32  `protobuf:"varint,3,req,name=chip" json:"chip,omitempty"`
	FinalChip        *int32  `protobuf:"varint,4,req,name=finalChip" json:"finalChip,omitempty"`
	TenthTimesLeft   *int32  `protobuf:"varint,5,req,name=tenthTimesLeft" json:"tenthTimesLeft,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *S2C_HeroRecruit) Reset()                    { *m = S2C_HeroRecruit{} }
func (m *S2C_HeroRecruit) String() string            { return proto.CompactTextString(m) }
func (*S2C_HeroRecruit) ProtoMessage()               {}
func (*S2C_HeroRecruit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{43} }

func (m *S2C_HeroRecruit) GetHeroIds() []int32 {
	if m != nil {
		return m.HeroIds
	}
	return nil
}

func (m *S2C_HeroRecruit) GetToChipHeroIds() []int32 {
	if m != nil {
		return m.ToChipHeroIds
	}
	return nil
}

func (m *S2C_HeroRecruit) GetChip() int32 {
	if m != nil && m.Chip != nil {
		return *m.Chip
	}
	return 0
}

func (m *S2C_HeroRecruit) GetFinalChip() int32 {
	if m != nil && m.FinalChip != nil {
		return *m.FinalChip
	}
	return 0
}

func (m *S2C_HeroRecruit) GetTenthTimesLeft() int32 {
	if m != nil && m.TenthTimesLeft != nil {
		return *m.TenthTimesLeft
	}
	return 0
}

// --411
type C2S_FreeHeroRecruit struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *C2S_FreeHeroRecruit) Reset()                    { *m = C2S_FreeHeroRecruit{} }
func (m *C2S_FreeHeroRecruit) String() string            { return proto.CompactTextString(m) }
func (*C2S_FreeHeroRecruit) ProtoMessage()               {}
func (*C2S_FreeHeroRecruit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{44} }

// --412
type S2C_FreeHeroRecruit struct {
	HeroId           *int32 `protobuf:"varint,1,req,name=heroId" json:"heroId,omitempty"`
	Chip             *int32 `protobuf:"varint,2,req,name=chip" json:"chip,omitempty"`
	FinalChip        *int32 `protobuf:"varint,3,req,name=finalChip" json:"finalChip,omitempty"`
	SecondsLeft      *int32 `protobuf:"varint,4,req,name=secondsLeft" json:"secondsLeft,omitempty"`
	TenthTimesLeft   *int32 `protobuf:"varint,5,req,name=tenthTimesLeft" json:"tenthTimesLeft,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *S2C_FreeHeroRecruit) Reset()                    { *m = S2C_FreeHeroRecruit{} }
func (m *S2C_FreeHeroRecruit) String() string            { return proto.CompactTextString(m) }
func (*S2C_FreeHeroRecruit) ProtoMessage()               {}
func (*S2C_FreeHeroRecruit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{45} }

func (m *S2C_FreeHeroRecruit) GetHeroId() int32 {
	if m != nil && m.HeroId != nil {
		return *m.HeroId
	}
	return 0
}

func (m *S2C_FreeHeroRecruit) GetChip() int32 {
	if m != nil && m.Chip != nil {
		return *m.Chip
	}
	return 0
}

func (m *S2C_FreeHeroRecruit) GetFinalChip() int32 {
	if m != nil && m.FinalChip != nil {
		return *m.FinalChip
	}
	return 0
}

func (m *S2C_FreeHeroRecruit) GetSecondsLeft() int32 {
	if m != nil && m.SecondsLeft != nil {
		return *m.SecondsLeft
	}
	return 0
}

func (m *S2C_FreeHeroRecruit) GetTenthTimesLeft() int32 {
	if m != nil && m.TenthTimesLeft != nil {
		return *m.TenthTimesLeft
	}
	return 0
}

// //////////////////////////////////////pve_level   begin-------------------------------------------**
// --701
type C2S_FightPVE struct {
	LevelId          *int32 `protobuf:"varint,1,req,name=levelId" json:"levelId,omitempty"`
	ArmyId           *int32 `protobuf:"varint,2,req,name=armyId" json:"armyId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *C2S_FightPVE) Reset()                    { *m = C2S_FightPVE{} }
func (m *C2S_FightPVE) String() string            { return proto.CompactTextString(m) }
func (*C2S_FightPVE) ProtoMessage()               {}
func (*C2S_FightPVE) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{46} }

func (m *C2S_FightPVE) GetLevelId() int32 {
	if m != nil && m.LevelId != nil {
		return *m.LevelId
	}
	return 0
}

func (m *C2S_FightPVE) GetArmyId() int32 {
	if m != nil && m.ArmyId != nil {
		return *m.ArmyId
	}
	return 0
}

// --702
type S2C_FightPVE struct {
	Rounds           []*Round `protobuf:"bytes,1,rep,name=rounds" json:"rounds,omitempty"`
	Useless          *int32   `protobuf:"varint,2,req,name=useless" json:"useless,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *S2C_FightPVE) Reset()                    { *m = S2C_FightPVE{} }
func (m *S2C_FightPVE) String() string            { return proto.CompactTextString(m) }
func (*S2C_FightPVE) ProtoMessage()               {}
func (*S2C_FightPVE) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{47} }

func (m *S2C_FightPVE) GetRounds() []*Round {
	if m != nil {
		return m.Rounds
	}
	return nil
}

func (m *S2C_FightPVE) GetUseless() int32 {
	if m != nil && m.Useless != nil {
		return *m.Useless
	}
	return 0
}

// --703
type C2S_GetPVELevelId struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *C2S_GetPVELevelId) Reset()                    { *m = C2S_GetPVELevelId{} }
func (m *C2S_GetPVELevelId) String() string            { return proto.CompactTextString(m) }
func (*C2S_GetPVELevelId) ProtoMessage()               {}
func (*C2S_GetPVELevelId) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{48} }

// --704
type S2C_GetPVELevelId struct {
	LevelId          *int32 `protobuf:"varint,1,req,name=levelId" json:"levelId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *S2C_GetPVELevelId) Reset()                    { *m = S2C_GetPVELevelId{} }
func (m *S2C_GetPVELevelId) String() string            { return proto.CompactTextString(m) }
func (*S2C_GetPVELevelId) ProtoMessage()               {}
func (*S2C_GetPVELevelId) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{49} }

func (m *S2C_GetPVELevelId) GetLevelId() int32 {
	if m != nil && m.LevelId != nil {
		return *m.LevelId
	}
	return 0
}

// --705
type C2S_ContinueFight struct {
	SkillId1         *int32 `protobuf:"varint,1,req,name=skillId1" json:"skillId1,omitempty"`
	SkillId2         *int32 `protobuf:"varint,2,req,name=skillId2" json:"skillId2,omitempty"`
	SkillId3         *int32 `protobuf:"varint,3,req,name=skillId3" json:"skillId3,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *C2S_ContinueFight) Reset()                    { *m = C2S_ContinueFight{} }
func (m *C2S_ContinueFight) String() string            { return proto.CompactTextString(m) }
func (*C2S_ContinueFight) ProtoMessage()               {}
func (*C2S_ContinueFight) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{50} }

func (m *C2S_ContinueFight) GetSkillId1() int32 {
	if m != nil && m.SkillId1 != nil {
		return *m.SkillId1
	}
	return 0
}

func (m *C2S_ContinueFight) GetSkillId2() int32 {
	if m != nil && m.SkillId2 != nil {
		return *m.SkillId2
	}
	return 0
}

func (m *C2S_ContinueFight) GetSkillId3() int32 {
	if m != nil && m.SkillId3 != nil {
		return *m.SkillId3
	}
	return 0
}

// --706
type S2C_ContinueFight struct {
	Rounds           []*Round `protobuf:"bytes,1,rep,name=rounds" json:"rounds,omitempty"`
	Useless          *int32   `protobuf:"varint,2,req,name=useless" json:"useless,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *S2C_ContinueFight) Reset()                    { *m = S2C_ContinueFight{} }
func (m *S2C_ContinueFight) String() string            { return proto.CompactTextString(m) }
func (*S2C_ContinueFight) ProtoMessage()               {}
func (*S2C_ContinueFight) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{51} }

func (m *S2C_ContinueFight) GetRounds() []*Round {
	if m != nil {
		return m.Rounds
	}
	return nil
}

func (m *S2C_ContinueFight) GetUseless() int32 {
	if m != nil && m.Useless != nil {
		return *m.Useless
	}
	return 0
}

func init() {
	proto.RegisterType((*C2S_Login)(nil), "king.C2S_Login")
	proto.RegisterType((*S2C_Login)(nil), "king.S2C_Login")
	proto.RegisterType((*S2C_ErrMsg)(nil), "king.S2C_ErrMsg")
	proto.RegisterType((*C2S_Ping)(nil), "king.C2S_Ping")
	proto.RegisterType((*S2C_Ping)(nil), "king.S2C_Ping")
	proto.RegisterType((*C2S_Heart)(nil), "king.C2S_Heart")
	proto.RegisterType((*S2C_Heart)(nil), "king.S2C_Heart")
	proto.RegisterType((*C2S_ReConnect)(nil), "king.C2S_ReConnect")
	proto.RegisterType((*S2C_ReConnect)(nil), "king.S2C_ReConnect")
	proto.RegisterType((*C2S_GetInitGame)(nil), "king.C2S_GetInitGame")
	proto.RegisterType((*Hero)(nil), "king.Hero")
	proto.RegisterType((*PlayerInfo)(nil), "king.PlayerInfo")
	proto.RegisterType((*Building)(nil), "king.Building")
	proto.RegisterType((*Army)(nil), "king.Army")
	proto.RegisterType((*S2C_GetInitGame)(nil), "king.S2C_GetInitGame")
	proto.RegisterType((*C2S_AttackNpc)(nil), "king.C2S_AttackNpc")
	proto.RegisterType((*S2C_AttackNpc)(nil), "king.S2C_AttackNpc")
	proto.RegisterType((*C2S_AttackNpcReleaseSkill)(nil), "king.C2S_AttackNpcReleaseSkill")
	proto.RegisterType((*TargetBeAction)(nil), "king.TargetBeAction")
	proto.RegisterType((*BattleAction)(nil), "king.BattleAction")
	proto.RegisterType((*BattleEvent)(nil), "king.BattleEvent")
	proto.RegisterType((*Round)(nil), "king.Round")
	proto.RegisterType((*HeroResult)(nil), "king.HeroResult")
	proto.RegisterType((*BattleResult)(nil), "king.BattleResult")
	proto.RegisterType((*S2C_AttackNpcReleaseSkill)(nil), "king.S2C_AttackNpcReleaseSkill")
	proto.RegisterType((*C2S_Sign)(nil), "king.C2S_Sign")
	proto.RegisterType((*GiftInfo)(nil), "king.GiftInfo")
	proto.RegisterType((*S2C_Sign)(nil), "king.S2C_Sign")
	proto.RegisterType((*C2S_GetSignInfo)(nil), "king.C2S_GetSignInfo")
	proto.RegisterType((*S2C_GetSignInfo)(nil), "king.S2C_GetSignInfo")
	proto.RegisterType((*C2S_GetRedPoint)(nil), "king.C2S_GetRedPoint")
	proto.RegisterType((*S2C_GetRedPoint)(nil), "king.S2C_GetRedPoint")
	proto.RegisterType((*C2S_GetRankInfo)(nil), "king.C2S_GetRankInfo")
	proto.RegisterType((*S2C_GetRankInfo)(nil), "king.S2C_GetRankInfo")
	proto.RegisterType((*C2S_BuyHero)(nil), "king.C2S_BuyHero")
	proto.RegisterType((*S2C_BuyHero)(nil), "king.S2C_BuyHero")
	proto.RegisterType((*C2S_EnQueue)(nil), "king.C2S_EnQueue")
	proto.RegisterType((*S2C_EnQueue)(nil), "king.S2C_EnQueue")
	proto.RegisterType((*C2S_SetDefArmy)(nil), "king.C2S_SetDefArmy")
	proto.RegisterType((*S2C_SetDefArmy)(nil), "king.S2C_SetDefArmy")
	proto.RegisterType((*C2S_EnQueueSingle)(nil), "king.C2S_EnQueueSingle")
	proto.RegisterType((*S2C_EnQueueSingle)(nil), "king.S2C_EnQueueSingle")
	proto.RegisterType((*C2S_HeroRecruit)(nil), "king.C2S_HeroRecruit")
	proto.RegisterType((*S2C_HeroRecruit)(nil), "king.S2C_HeroRecruit")
	proto.RegisterType((*C2S_FreeHeroRecruit)(nil), "king.C2S_FreeHeroRecruit")
	proto.RegisterType((*S2C_FreeHeroRecruit)(nil), "king.S2C_FreeHeroRecruit")
	proto.RegisterType((*C2S_FightPVE)(nil), "king.C2S_FightPVE")
	proto.RegisterType((*S2C_FightPVE)(nil), "king.S2C_FightPVE")
	proto.RegisterType((*C2S_GetPVELevelId)(nil), "king.C2S_GetPVELevelId")
	proto.RegisterType((*S2C_GetPVELevelId)(nil), "king.S2C_GetPVELevelId")
	proto.RegisterType((*C2S_ContinueFight)(nil), "king.C2S_ContinueFight")
	proto.RegisterType((*S2C_ContinueFight)(nil), "king.S2C_ContinueFight")
}

func init() { proto.RegisterFile("king.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1509 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0x5d, 0x6f, 0x1b, 0x45,
	0x17, 0x96, 0x3f, 0x63, 0x1f, 0xe7, 0xa3, 0xd9, 0xf6, 0xcd, 0xbb, 0x7d, 0xdf, 0x0a, 0x45, 0x03,
	0x94, 0x0a, 0x95, 0x8a, 0xba, 0x14, 0xf5, 0x02, 0xaa, 0x26, 0x69, 0x48, 0x8d, 0xdc, 0x12, 0x36,
	0x29, 0x5c, 0x20, 0x54, 0x6d, 0xbc, 0x13, 0x7b, 0x94, 0xf5, 0xcc, 0x6a, 0x77, 0xec, 0xd6, 0x12,
	0xbf, 0x81, 0x2b, 0x10, 0xf7, 0xdc, 0x21, 0x2e, 0xf9, 0x05, 0xfc, 0x1d, 0x7e, 0x05, 0x3a, 0xf3,
	0xb1, 0x3b, 0xbb, 0xb5, 0x0b, 0x14, 0xc4, 0xdd, 0x3c, 0x67, 0xce, 0x9c, 0xcf, 0x67, 0xce, 0xce,
	0x02, 0x5c, 0x30, 0x3e, 0xbe, 0x95, 0xa4, 0x42, 0x0a, 0xaf, 0x89, 0x6b, 0xf2, 0x29, 0x74, 0x0f,
	0xfa, 0x27, 0xcf, 0x86, 0x62, 0xcc, 0xb8, 0xf7, 0x5f, 0x58, 0x13, 0x09, 0xe5, 0xcf, 0x58, 0xe4,
	0xd7, 0x76, 0xeb, 0x37, 0xba, 0x41, 0x1b, 0xe1, 0x20, 0xf2, 0x3c, 0x68, 0xf2, 0x70, 0x4a, 0xfd,
	0xba, 0x92, 0xaa, 0xb5, 0x77, 0x09, 0x1a, 0xb3, 0x34, 0xf6, 0x1b, 0x4a, 0x84, 0x4b, 0x72, 0x1f,
	0xba, 0x27, 0xfd, 0x03, 0x63, 0xeb, 0xff, 0xd0, 0x4d, 0xe2, 0x70, 0x41, 0x53, 0x6b, 0xad, 0x15,
	0x74, 0xb4, 0x60, 0x10, 0x79, 0x57, 0xa0, 0x25, 0xc5, 0x05, 0xe5, 0xc6, 0xa0, 0x06, 0xe4, 0x1e,
	0x00, 0x9e, 0x3f, 0x4c, 0xd3, 0xc7, 0xd9, 0x18, 0xed, 0xd3, 0x34, 0x35, 0x47, 0x71, 0xe9, 0xf9,
	0xb0, 0xa6, 0x42, 0x1f, 0x44, 0xea, 0x5c, 0x2b, 0xb0, 0x90, 0x7c, 0x00, 0x1d, 0xcc, 0xe2, 0x98,
	0xf1, 0xb1, 0x77, 0x03, 0xb6, 0x46, 0x31, 0xa3, 0x5c, 0x9e, 0xb2, 0x29, 0xcd, 0x64, 0x38, 0x4d,
	0x8c, 0x8d, 0xaa, 0x18, 0x4f, 0xa1, 0xbf, 0xbf, 0x78, 0xaa, 0xa7, 0x2b, 0xf6, 0x88, 0x86, 0xa9,
	0x24, 0x77, 0x75, 0xca, 0x0a, 0xa0, 0x8d, 0x8c, 0xa6, 0x73, 0x9a, 0xbe, 0x64, 0xa3, 0x22, 0x26,
	0x5f, 0xc1, 0x06, 0xda, 0x08, 0xe8, 0x81, 0xe0, 0x9c, 0x8e, 0xe4, 0xea, 0xca, 0x97, 0xca, 0x58,
	0x5f, 0x55, 0xc6, 0x86, 0x5b, 0xc6, 0x9b, 0xb0, 0x81, 0x31, 0x15, 0xc6, 0x5f, 0xd5, 0x0a, 0xb2,
	0x0d, 0x5b, 0x18, 0xca, 0x11, 0x95, 0x03, 0xce, 0xe4, 0x51, 0x38, 0xa5, 0xe4, 0xb7, 0x1a, 0x34,
	0x1f, 0xd1, 0x54, 0x78, 0x9b, 0x50, 0xcf, 0x4f, 0xd4, 0x59, 0xa4, 0x5a, 0xf2, 0x22, 0x31, 0x61,
	0xe0, 0x12, 0x23, 0x88, 0xe9, 0x9c, 0x6a, 0x1a, 0xb4, 0x02, 0x0d, 0x90, 0x2e, 0x99, 0x0c, 0x53,
	0xbf, 0xa9, 0x84, 0x6a, 0xed, 0xed, 0x40, 0x3b, 0x4c, 0xa7, 0x8b, 0xe1, 0xdc, 0x6f, 0x29, 0xa9,
	0x41, 0x1e, 0x81, 0x75, 0x5c, 0x9d, 0x5c, 0xb0, 0x38, 0xbe, 0x3d, 0x9c, 0xfb, 0x6d, 0xb5, 0x5b,
	0x92, 0x95, 0x74, 0xfa, 0xc3, 0xb9, 0xbf, 0x56, 0xd1, 0xe9, 0x57, 0x74, 0xee, 0x0c, 0xe7, 0x7e,
	0xa7, 0xa2, 0x73, 0x67, 0x38, 0xc7, 0xb8, 0x46, 0x13, 0x96, 0xf8, 0x5d, 0x1d, 0x17, 0xae, 0xc9,
	0x77, 0x35, 0x80, 0x63, 0x5d, 0x0c, 0x7e, 0x2e, 0x94, 0x8a, 0x60, 0xdc, 0x24, 0xad, 0xd6, 0xc8,
	0xbb, 0x88, 0x85, 0x53, 0xc1, 0x73, 0xde, 0x19, 0xb8, 0x3a, 0xfd, 0xe7, 0x42, 0x44, 0x36, 0x7d,
	0x5c, 0xa3, 0x8d, 0x29, 0xe3, 0x34, 0x0d, 0x63, 0x93, 0xbf, 0x85, 0x68, 0x63, 0x9c, 0x86, 0x8c,
	0x9b, 0xcc, 0x35, 0x20, 0xf7, 0xa1, 0xb3, 0x3f, 0x63, 0x71, 0x84, 0xdc, 0xf4, 0x61, 0xed, 0x3c,
	0x4c, 0xa7, 0x58, 0x1d, 0x1d, 0x96, 0x85, 0x76, 0x07, 0x6b, 0x52, 0x2f, 0x76, 0xfa, 0xc3, 0x39,
	0xb9, 0x07, 0xcd, 0xbd, 0x74, 0xba, 0xb0, 0x65, 0x1f, 0xd8, 0x36, 0x1a, 0x84, 0x27, 0x27, 0x34,
	0x15, 0x83, 0x28, 0xf3, 0xeb, 0xbb, 0x0d, 0x3c, 0x69, 0x20, 0xf9, 0xa5, 0x06, 0x5b, 0xc8, 0x1f,
	0x87, 0x11, 0xde, 0x2e, 0xb4, 0xf0, 0x5c, 0xe6, 0xd7, 0x76, 0x1b, 0x37, 0x7a, 0x7d, 0xb8, 0xa5,
	0xe6, 0x08, 0x3a, 0x08, 0xf4, 0x86, 0xf7, 0x2e, 0x74, 0xce, 0x4c, 0xbc, 0x2a, 0x94, 0x5e, 0x7f,
	0x53, 0x2b, 0xd9, 0x2c, 0x82, 0x7c, 0x1f, 0xad, 0xa1, 0xb3, 0xcc, 0x6f, 0xb8, 0xd6, 0x90, 0x71,
	0x81, 0xde, 0xf0, 0xde, 0x07, 0x48, 0xf2, 0x9e, 0xa8, 0x3a, 0xf6, 0xfa, 0x97, 0xb4, 0x5a, 0xd1,
	0xab, 0xc0, 0xd1, 0x21, 0x1f, 0xeb, 0x1b, 0xb5, 0x27, 0x65, 0x38, 0xba, 0x78, 0x92, 0x8c, 0x56,
	0x26, 0x7e, 0x05, 0x5a, 0x3c, 0x19, 0xe5, 0x23, 0x44, 0x03, 0x3c, 0x8e, 0x39, 0xbf, 0xee, 0xf1,
	0xaf, 0xe1, 0x6a, 0xc9, 0x7b, 0x40, 0x63, 0x1a, 0x66, 0x54, 0x11, 0x0f, 0x4d, 0xe9, 0xda, 0x5a,
	0x53, 0x1a, 0xa1, 0xa9, 0x54, 0xcc, 0x72, 0x52, 0x69, 0xa0, 0xef, 0x0e, 0x4d, 0x0c, 0xa3, 0xd4,
	0x9a, 0x3c, 0x81, 0xcd, 0xd3, 0x30, 0x1d, 0x53, 0xb9, 0x4f, 0xf7, 0x46, 0x92, 0x09, 0x8e, 0x37,
	0x31, 0x11, 0x99, 0x1d, 0x8e, 0x89, 0xc8, 0xd0, 0xcb, 0x3c, 0x8c, 0x67, 0xd4, 0xf6, 0xd3, 0x20,
	0xb4, 0x27, 0x17, 0x09, 0xb5, 0xf6, 0x70, 0x4d, 0x7e, 0xac, 0xc1, 0xfa, 0x7e, 0x28, 0x65, 0x6c,
	0xcd, 0x5d, 0x83, 0x6e, 0xa8, 0x62, 0x3f, 0xce, 0x8d, 0x16, 0x02, 0xe4, 0x4a, 0x86, 0x99, 0x14,
	0x73, 0xd7, 0x40, 0xef, 0x3e, 0x6c, 0xc9, 0x52, 0x60, 0xb6, 0xa7, 0x57, 0x74, 0xb3, 0xca, 0x51,
	0x07, 0x55, 0x65, 0xef, 0x7f, 0xd0, 0xa1, 0x73, 0xca, 0x25, 0xd2, 0xb0, 0xa9, 0xc2, 0xce, 0x31,
	0x39, 0x80, 0x9e, 0x8e, 0xf1, 0x10, 0x25, 0xcb, 0x66, 0x11, 0x56, 0xa0, 0x5e, 0x54, 0x60, 0x59,
	0xa6, 0xdf, 0xd6, 0xa0, 0x15, 0xa8, 0xba, 0xde, 0x83, 0x8d, 0x33, 0x27, 0x65, 0x4b, 0x65, 0xcf,
	0xb0, 0xd4, 0xd9, 0x0a, 0xca, 0x8a, 0xde, 0x5d, 0x58, 0x3f, 0x2b, 0x02, 0xd1, 0xf5, 0xed, 0xf5,
	0xb7, 0xdd, 0x83, 0x6a, 0x27, 0x28, 0xa9, 0x15, 0xed, 0x6d, 0x38, 0xed, 0x25, 0x1c, 0x40, 0x11,
	0x9d, 0x66, 0xb3, 0x58, 0x2e, 0x6f, 0xa3, 0x21, 0x4b, 0xbd, 0x44, 0x96, 0x1d, 0x68, 0xcb, 0x54,
	0x88, 0x24, 0x33, 0xe6, 0x0c, 0xf2, 0xde, 0x00, 0x60, 0x9c, 0xc9, 0x53, 0xbd, 0xa7, 0x27, 0x8e,
	0x23, 0x21, 0x3f, 0xe4, 0xad, 0x36, 0x2e, 0x57, 0x11, 0xfb, 0x4d, 0x68, 0xab, 0x08, 0x6d, 0x7e,
	0x3d, 0x9d, 0x9f, 0x2a, 0x5e, 0x60, 0xb6, 0xf0, 0x70, 0xaa, 0xcc, 0xd8, 0x28, 0x34, 0xf2, 0xfa,
	0xd0, 0x9b, 0xe4, 0x59, 0xe9, 0x56, 0xe6, 0x17, 0xb6, 0x48, 0x37, 0x70, 0x95, 0xc8, 0xf7, 0x35,
	0xb8, 0x5a, 0xba, 0x73, 0xa5, 0x4b, 0xf3, 0xa1, 0x2d, 0xba, 0x56, 0x57, 0xc1, 0x56, 0xba, 0x65,
	0x8c, 0x96, 0xf4, 0x56, 0xd6, 0x6f, 0x69, 0x37, 0xf2, 0xcb, 0xd6, 0x74, 0x2e, 0xdb, 0x75, 0xfd,
	0x96, 0x38, 0x61, 0x63, 0x8e, 0xfc, 0xcc, 0xd8, 0x98, 0x9f, 0x22, 0xad, 0xcc, 0x87, 0xd3, 0x62,
	0xf2, 0x11, 0x74, 0x8e, 0xd8, 0xb9, 0x54, 0x5f, 0x8d, 0x1d, 0x68, 0x8f, 0x71, 0x9d, 0x17, 0x55,
	0x23, 0xbc, 0x39, 0xb8, 0x7a, 0x32, 0x9b, 0xda, 0x9b, 0x63, 0x20, 0xf9, 0x46, 0xbf, 0x3d, 0xfe,
	0xc8, 0x8b, 0x77, 0x1d, 0x2b, 0xfe, 0x3c, 0x4c, 0x23, 0xd3, 0x16, 0x33, 0x55, 0xad, 0xe7, 0xc0,
	0xec, 0x7a, 0x37, 0xa1, 0x4b, 0x5f, 0xc8, 0x40, 0xab, 0x36, 0x96, 0xaa, 0x16, 0x0a, 0xce, 0x47,
	0x1f, 0x03, 0x50, 0x03, 0xf4, 0xd7, 0x62, 0xec, 0x5b, 0x99, 0xb7, 0x0b, 0xbd, 0xe7, 0x94, 0x5e,
	0x20, 0x7e, 0x18, 0x2e, 0x4c, 0x6c, 0xae, 0xc8, 0xbb, 0x0e, 0x9b, 0x67, 0x5f, 0x1a, 0x7c, 0x2a,
	0xa2, 0x70, 0xa1, 0xf2, 0xec, 0x04, 0x15, 0x29, 0x7e, 0x9d, 0xa7, 0x82, 0xcb, 0x89, 0x35, 0xa5,
	0xbb, 0x50, 0x92, 0xe1, 0xf3, 0xe9, 0xec, 0xb1, 0x15, 0x68, 0x63, 0x4d, 0x65, 0xac, 0x2a, 0xc6,
	0x72, 0x63, 0x10, 0x83, 0xc8, 0xbe, 0x25, 0x34, 0x72, 0xd2, 0x0a, 0x68, 0x74, 0x2c, 0x18, 0x97,
	0xe4, 0xb3, 0x3c, 0x2b, 0x2b, 0xc2, 0x61, 0x97, 0x47, 0xa7, 0x72, 0xea, 0x04, 0x85, 0x00, 0x2f,
	0x94, 0x76, 0x87, 0x2d, 0x30, 0xd9, 0x38, 0x12, 0xd7, 0x47, 0xc8, 0x2f, 0x54, 0xe9, 0xde, 0x29,
	0x7c, 0x18, 0x11, 0xd2, 0x2d, 0x1b, 0x89, 0xd4, 0xf6, 0x53, 0x03, 0xb2, 0x07, 0x3d, 0x3c, 0xbb,
	0x3f, 0x5b, 0xa8, 0xe7, 0xd5, 0x0e, 0xb4, 0xb3, 0x89, 0x48, 0x0a, 0xd6, 0x68, 0x84, 0x7c, 0xb0,
	0xcf, 0xb3, 0xea, 0x93, 0x8f, 0x84, 0xd0, 0x43, 0x5f, 0xd6, 0x84, 0xf3, 0x19, 0xaf, 0x95, 0x3e,
	0xe3, 0xf9, 0x5b, 0xa7, 0x5e, 0xbc, 0x75, 0xbc, 0xb7, 0x60, 0x43, 0x8a, 0x83, 0x09, 0x4b, 0x1e,
	0x99, 0x33, 0x0d, 0x75, 0xa6, 0x2c, 0x24, 0x99, 0x8e, 0xf2, 0x90, 0x7f, 0x3e, 0xa3, 0x33, 0x5a,
	0xb8, 0xb8, 0x6d, 0x5f, 0x1f, 0x06, 0x16, 0x3b, 0x7d, 0xcb, 0x6e, 0x03, 0x8b, 0x9d, 0x3b, 0xa6,
	0xd3, 0x16, 0x3a, 0xe3, 0xa7, 0xe9, 0x8e, 0x1f, 0x74, 0xaa, 0xde, 0xfe, 0xff, 0xaa, 0xd3, 0x07,
	0xb0, 0xa9, 0xae, 0x3a, 0x95, 0x0f, 0xe9, 0xf9, 0x2b, 0x9f, 0x4b, 0x3b, 0xd0, 0x1e, 0x31, 0xb9,
	0x28, 0xc6, 0x8a, 0x46, 0x68, 0x41, 0x5d, 0xe3, 0xd7, 0xb7, 0xf0, 0x14, 0xb6, 0x9d, 0x6a, 0x9f,
	0x30, 0x3e, 0x8e, 0xe9, 0xca, 0x27, 0xc3, 0xcb, 0x1f, 0xbd, 0xc2, 0x5d, 0xa3, 0x94, 0xda, 0x53,
	0xd8, 0x76, 0xea, 0xf9, 0x8f, 0x99, 0x7d, 0x5b, 0xb3, 0x5f, 0xcf, 0xf4, 0x51, 0x3a, 0x63, 0x32,
	0xff, 0xec, 0xd6, 0x9c, 0xcf, 0xee, 0xcf, 0x66, 0x98, 0xb8, 0x7a, 0xab, 0xa9, 0xfa, 0x12, 0x2d,
	0xeb, 0x4b, 0x68, 0x99, 0x13, 0xba, 0xe1, 0x10, 0xfa, 0x1a, 0x74, 0xcf, 0x19, 0x0f, 0x63, 0xd4,
	0x33, 0xbd, 0x2d, 0x04, 0x38, 0x9c, 0x24, 0xe5, 0x72, 0xa2, 0xfe, 0xbb, 0x86, 0xf4, 0x5c, 0x9a,
	0x71, 0x51, 0x91, 0x92, 0xff, 0xc0, 0x65, 0x4c, 0xea, 0x93, 0x94, 0x52, 0x27, 0x60, 0xf2, 0x53,
	0x0d, 0x2e, 0x63, 0x12, 0x15, 0xf9, 0xca, 0x2a, 0x2e, 0xbb, 0x71, 0xa5, 0x00, 0x1b, 0xd5, 0x00,
	0x77, 0xa1, 0x97, 0xd1, 0x91, 0xe0, 0x91, 0x8e, 0x4e, 0x27, 0xe0, 0x8a, 0xfe, 0x74, 0x0a, 0x0f,
	0x60, 0x5d, 0xa5, 0xc0, 0xc6, 0x13, 0x79, 0xfc, 0xc5, 0x21, 0x16, 0x5b, 0xfd, 0x8b, 0xe4, 0x41,
	0x5a, 0xe8, 0x74, 0xb6, 0x5e, 0xea, 0xec, 0x63, 0x58, 0x57, 0xc9, 0x5a, 0x0b, 0xc5, 0x7b, 0xa0,
	0xb6, 0xfa, 0x3d, 0xe0, 0xc3, 0xda, 0x2c, 0xa3, 0x31, 0xcd, 0x2c, 0x79, 0x2c, 0x24, 0x97, 0x35,
	0xad, 0x8f, 0x28, 0x1a, 0x1b, 0x6a, 0xdf, 0xe4, 0x3d, 0x4d, 0xca, 0x92, 0x70, 0x75, 0xa8, 0x64,
	0xac, 0x6d, 0x1c, 0x08, 0x2e, 0x19, 0x9f, 0x51, 0x15, 0x9a, 0xfa, 0x58, 0xea, 0xd7, 0xe7, 0xed,
	0xfc, 0x63, 0x69, 0xb0, 0xb3, 0x67, 0x87, 0x43, 0x8e, 0x9d, 0x3d, 0x3b, 0x1e, 0x72, 0x4c, 0x02,
	0x1d, 0x57, 0xd9, 0xd1, 0xdf, 0x2b, 0xc0, 0xef, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa3, 0x40, 0xa9,
	0x27, 0x6b, 0x11, 0x00, 0x00,
}
